language: node_js
node_js:
  - 7
  - 8
  - 9
cache:
  directories:
    - node_modules
install:
  - npm prune
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm run test:src:coverage
  - npm run build:code
  - npm run test:build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
