language: node_js
node_js:
  - 7
  - 8
  - 9
cache:
  directories:
    - node_modules
install:
  - npm prune
  - npm install
script:
  - npm run lint
  - npm run test:src:coverage
  - npm run build:code
  - npm run test:build
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
