language: node_js
node_js:
  - 7
  - 8
  - 9
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
